# Configuración de Eureka
spring:
  application:
    name: microserviceMensajeria  # Nombre del microservicio en Eureka
  cloud:
    discovery:
      enabled: true  # Habilitar descubrimiento de servicios
  kafka:
    bootstrap-servers: localhost:9092  # Dirección del servidor Kafka
    consumer:
      group-id: message-service  # ID del grupo de consumidores
      auto-offset-reset: earliest  # Comportamiento al leer los mensajes (por ejemplo, empezar desde el primer mensaje)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Serializador para las claves de los mensajes
      value-serializer: org.apache.kafka.common.serialization.StringSerializer  # Serializador para los valores de los mensajes
   

  
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/  # URL del servidor Eureka
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}  # ID único para la instancia

# Configuración del puerto del servidor
server:
  port: 808  # Puerto en el que escuchará el microservicio (puede usar variables de entorno como ${PORT})

